### ISSUE TITLE
Returning team is not able to select a team 

### ISSUE THREAD

**Issue by mizanul** [zrdev/zrdev.github.io#59]

**Comment by ghost** [comment]
This is not a bug. The old team rosters are just not there anymore
(and can't be imported because the email addresses used for old
accounts may not be associated with Google accounts), so for this year
they just need to register as a new team and note somewhere that they
are returning so we can match them up.

**Comment by mizanul** [comment]
Comments from Wendy:

For now would it be easier to ask them to fill in their prior year’s team number in the application rather than trying to link to it?   It seems that the link is currently made through the email and that this is varying from year to year.

**Comment by ghost** [comment]
A note has been added to the form telling them to fill in their info and make a note if they don't see the team name.
